[build]
  command = "npm run docs"
  publish = "docs/dist/"

[build.environment]
  DEBUG = "mocha:docs*"
  NODE_VERSION = "24"

[context.deploy-preview]
  command = "npm run docs"
  publish = "docs/dist/"
