jobs:
  octoguide:
    if: ${{ !endsWith(github.actor, '[bot]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: OctoGuide/bot@0.18.1
        with:
          config: recommended
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-header: "Octobot Response:"
          include-bots: "false"
          include-associations: "FIRST_TIMER,FIRST_TIME_CONTRIBUTOR,CONTRIBUTOR,MEMBER"
          pr-body-descriptive: "true"
          comment-meaningful: "true"
          pr-title-conventional: "true"
          pr-linked-issue: "true"
          pr-task-completion: "true"
          text-image-alt-text: "true"

name: OctoGuide

on:
  discussion:
    types: [created, edited]
  discussion_comment:
    types: [created, deleted, edited]
  issue_comment:
    types: [created, deleted, edited]
  issues:
    types: [edited, opened]
  pull_request_review_comment:
    types: [created, deleted, edited]
  pull_request_target:
    types: [edited, opened]

permissions:
  discussions: write
  issues: write
  pull-requests: write
